"""
/***************************************************************************
 BDOT10k_GML_SHP_Loader
                                 A QGIS plugin
 Importuje BDOT10k w formacie GML albo SHP
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Marcin Lebiecki / Główny Urząd Geodezji i Kartografii
        email                : marcin.lebiecki@gugik.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
"""Punkt wejścia wtyczki BDOT10k_GML_SHP_Loader dla QGIS."""


def classFactory(iface):  # pylint: disable=invalid-name
    """Utwórz instancję głównej klasy wtyczki dla przekazanego interfejsu QGIS."""
    from .BDOT10k_GML_SHP_Loader import BDOT10k_GML_SHP_Loader

    return BDOT10k_GML_SHP_Loader(iface)
