"""
/***************************************************************************
 BDOT10k_GML_SHP_Loader
                                 A QGIS plugin
 Importuje BDOT10k w formacie GML albo SHP
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Marcin Lebiecki / Główny Urząd Geodezji i Kartografii
        email                : marcin.lebiecki@gugik.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
"""Wtyczka QGIS do wczytywania i symbolizacji danych BDOT10k w GML lub SHP."""

import re
import shutil
import zipfile
from pathlib import Path, PurePosixPath

from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QApplication,
    QFileDialog,
    QMenu,
    QMessageBox,
    QProgressBar,
)
from qgis.core import (
    Qgis,
    QgsApplication,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsFeatureRequest,
    QgsProject,
    QgsSymbolLayerId,
    QgsSymbolLayerReference,
    QgsVectorFileWriter,
    QgsVectorLayer,
)

from . import resources
from .constants import POWIATY
from .geoportal import GeoportalDownloadDialog, download_geoportal_zip
from .help_tools import (
    BDOT10K_CURRENTNESS_WMS_URL,
    BDOT10K_MONITORING_WMS_URL,
    download_bdot10k_regulation,
    show_about_dialog,
    show_bdot10k_currentness_wms,
    show_bdot10k_monitoring_wms,
)
from .layer_specs import LAYER_SPECS


# Rozpoznawane są obie spotykane konwencje nazewnicze, np.:
# PL.PZGiK.200.0262__OT_... oraz PL.PZGiK.200.BDOT10k.0262__OT_...
_DATA_FILE_RE = re.compile(
    r"^(PL\.PZGiK\.\d{3,4}(?:\.BDOT10k)?\.\d{4})__OT_.+\.(xml|shp)$",
    re.IGNORECASE,
)


class BDOT10k_GML_SHP_Loader:
    """Główna klasa wtyczki."""

    def __init__(self, iface):
        """Zapisz interfejs QGIS i przygotuj tłumaczenia wtyczki."""
        self.iface = iface
        self.plugin_dir = Path(__file__).resolve().parent

        locale = str(QSettings().value("locale/userLocale", "en"))[:2]
        locale_path = self.plugin_dir / "i18n" / f"BDOT10k_GML_SHP_Loader_{locale}.qm"
        if locale_path.is_file():
            self.translator = QTranslator()
            self.translator.load(str(locale_path))
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr("&BDOT10k_GML_SHP")
        self.first_start = None
        self._available_source_uris = None

    @staticmethod
    def tr(message):
        """Zwróć przetłumaczony tekst interfejsu."""
        return QCoreApplication.translate("BDOT10k_GML_SHP_Loader", message)

    def _layer_feature_state(self, layer, context=""):
        """
        Zwróć ``(feature_count, has_features)`` dla warstwy.

        QGIS/OGR może zwrócić ``featureCount() == -1`` dla poprawnej warstwy
        GeoPackage. Wartość -1 oznacza wtedy, że liczba obiektów jest nieznana,
        a nie że warstwa jest pusta. W takim przypadku sprawdzamy istnienie
        pierwszego obiektu przez iterator.
        """
        try:
            count = layer.featureCount()
        except Exception:
            count = -1

        if count > 0:
            return count, True
        if count == 0:
            return count, False

        # count < 0 (najczęściej -1) = liczba nieznana.
        try:
            request = QgsFeatureRequest()
            request.setLimit(1)
            has_features = next(layer.getFeatures(request), None) is not None
            return count, has_features
        except Exception:
            # Nie odrzucamy poprawnej warstwy tylko dlatego, że provider nie
            # potrafi szybko podać liczby obiektów ani wykonać testu iteratora.
            return count, True

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Dodaj akcję wtyczki do menu i opcjonalnie do paska narzędzi."""
        action = QAction(QIcon(icon_path), text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
            action.setToolTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Utwórz pozycję menu i ikonę wtyczki."""
        self.add_action(
            ":/plugins/BDOT10k_GML_SHP_Loader/icon.png",
            text=self.tr("Wczytaj dane BDOT10k"),
            callback=self.run,
            status_tip=self.tr(
                "Wczytaj dane BDOT10k z katalogu, pliku ZIP albo pobierz je z Geoportalu."
            ),
            whats_this=self.tr(
                "Pozwala wybrać lokalne dane BDOT10k lub pobrać powiatową paczkę danych z Geoportalu GUGiK."
            ),
            parent=self.iface.mainWindow(),
        )
        self.first_start = True

    def unload(self):
        """Usuń elementy interfejsu dodane przez wtyczkę."""
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Wybierz źródło BDOT10k, zweryfikuj je i wczytaj warstwy."""
        if self.first_start:
            self.first_start = False

        source = self._select_source()
        if source is None:
            return

        dataset = self._prepare_source(*source)
        if dataset is None:
            return

        self._load_dataset(**dataset)

    def _close_plugin_windows(self):
        """Zamknij wszystkie aktualnie otwarte okna należące do wtyczki."""
        for widget in QApplication.topLevelWidgets():
            if widget.property("BDOT10k_GML_SHP_Loader_window"):
                widget.close()

    def _select_source(self):
        """Pozwól użytkownikowi wskazać katalog BDOT10k albo archiwum ZIP."""
        settings = QSettings()
        start_path = str(settings.value("BDOT10k_GML_SHP_Loader/lastSource", ""))

        choice = QMessageBox(self.iface.mainWindow())
        choice.setProperty("BDOT10k_GML_SHP_Loader_window", True)
        choice.setWindowTitle("Źródło danych BDOT10k")
        choice.setIcon(QMessageBox.Question)
        choice.setText("Wybierz sposób wczytania danych BDOT10k.")
        folder_button = choice.addButton("katalog", QMessageBox.AcceptRole)
        folder_button.setToolTip(
            "Wskaż katalog zawierający dane BDOT10k w formacie GML/XML lub SHP."
        )
        zip_button = choice.addButton("plik ZIP", QMessageBox.AcceptRole)
        zip_button.setToolTip(
            "Wskaż zapisany na komputerze plik ZIP zawierający dane BDOT10k."
        )
        geoportal_button = choice.addButton("Geoportal", QMessageBox.ActionRole)
        geoportal_button.setToolTip(
            "Wybierz powiat, pobierz jego paczkę BDOT10k z Geoportalu GUGiK i automatycznie wczytaj ją do QGIS."
        )

        # Menu pomocy zawiera materiały i usługi przydatne podczas pracy z BDOT10k.
        # HelpRole nie zamyka QMessageBox, dzięki czemu po użyciu jednej z pozycji
        # użytkownik może nadal wybrać sposób wczytania danych.
        help_button = choice.addButton("Pomoc", QMessageBox.HelpRole)
        help_button.setToolTip(
            "Otwórz menu pomocy z rozporządzeniem, mapami Geoportalu oraz informacjami o wtyczce."
        )
        help_menu = QMenu(help_button)
        # QAction pokazuje tooltip dopiero po włączeniu tej właściwości menu.
        help_menu.setToolTipsVisible(True)
        regulation_action = help_menu.addAction("Rozporządzenie BDOT10k (PDF)")
        regulation_action.setToolTip(
            "Pobierz oficjalny tekst rozporządzenia dotyczącego BDOT10k z systemu ELI."
        )
        regulation_action.triggered.connect(
            lambda: download_bdot10k_regulation(choice)
        )
        monitoring_action = help_menu.addAction("Monitoring pozyskiwania BDOT10k")
        monitoring_action.setToolTip(
            "Dodaj do bieżącego projektu QGIS mapę monitoringu pozyskiwania BDOT10k.\n"
            f"Źródło: {BDOT10K_MONITORING_WMS_URL}"
        )
        monitoring_action.triggered.connect(
            lambda: show_bdot10k_monitoring_wms(choice, self.iface)
        )

        currentness_action = help_menu.addAction("Aktualność BDOT10k")
        currentness_action.setToolTip(
            "Dodaj do bieżącego projektu QGIS mapę aktualności BDOT10k.\n"
            f"Źródło: {BDOT10K_CURRENTNESS_WMS_URL}"
        )
        currentness_action.triggered.connect(
            lambda: show_bdot10k_currentness_wms(choice, self.iface)
        )

        help_menu.addSeparator()
        info_action = help_menu.addAction("Informacje")
        info_action.setToolTip(
            "Wyświetl informacje o wtyczce, jej wersji, autorze i repozytorium."
        )
        info_action.triggered.connect(
            lambda: show_about_dialog(
                choice,
                self.plugin_dir,
                self._close_plugin_windows,
            )
        )
        help_button.setMenu(help_menu)

        cancel_button = choice.addButton("Anuluj", QMessageBox.RejectRole)
        cancel_button.setToolTip("Zamknij okno bez wczytywania danych.")
        choice.exec_()

        clicked = choice.clickedButton()
        if clicked is folder_button:
            folder = QFileDialog.getExistingDirectory(
                self.iface.mainWindow(),
                "Wybierz katalog BDOT10k",
                start_path,
            )
            if not folder:
                return None
            folder_path = Path(folder)
            settings.setValue("BDOT10k_GML_SHP_Loader/lastSource", str(folder_path.parent))
            return "folder", folder_path

        if clicked is zip_button:
            zip_name, _ = QFileDialog.getOpenFileName(
                self.iface.mainWindow(),
                "Wybierz plik ZIP z danymi BDOT10k",
                start_path,
                "Archiwa ZIP (*.zip)",
            )
            if not zip_name:
                return None
            zip_path = Path(zip_name)
            settings.setValue("BDOT10k_GML_SHP_Loader/lastSource", str(zip_path.parent))
            return "zip", zip_path

        if clicked is geoportal_button:
            dialog = GeoportalDownloadDialog(self.iface.mainWindow())
            dialog.setProperty("BDOT10k_GML_SHP_Loader_window", True)
            if dialog.exec_() != dialog.Accepted:
                return None

            zip_path = download_geoportal_zip(
                self.iface.mainWindow(),
                dialog.selected_teryt(),
                dialog.destination_directory(),
            )
            if zip_path is None:
                return None

            settings.setValue("BDOT10k_GML_SHP_Loader/lastSource", str(zip_path.parent))
            return "zip", zip_path

        return None

    def _prepare_source(self, source_type, source_path):
        """Rozpoznaj przestrzeń nazw i format danych dla katalogu albo ZIP."""
        try:
            if source_type == "folder":
                records = self._scan_folder(source_path)
            else:
                records = self._scan_zip(source_path)
        except (OSError, zipfile.BadZipFile) as exc:
            QMessageBox.critical(
                self.iface.mainWindow(),
                "BDOT10k",
                f"Nie można odczytać wskazanego źródła:\n{exc}",
            )
            return None

        if not records:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "BDOT10k",
                "Nie znaleziono plików BDOT10k w formacie GML/XML ani SHP.",
            )
            return None

        locations = sorted({(r["parent"], r["namespace"]) for r in records})
        if len(locations) != 1:
            names = "\n".join(
                f"• {namespace}" + (f" ({parent})" if parent else "")
                for parent, namespace in locations[:10]
            )
            QMessageBox.warning(
                self.iface.mainWindow(),
                "BDOT10k",
                "Wskazane źródło zawiera więcej niż jeden zbiór BDOT10k. "
                "Wskaż katalog lub ZIP zawierający jeden zbiór.\n\n" + names,
            )
            return None

        parent, namespace = locations[0]
        formats = sorted({r["format"] for r in records if r["parent"] == parent and r["namespace"] == namespace})
        data_format = self._choose_format(formats)
        if data_format is None:
            return None

        if source_type == "folder":
            prefix = source_path.resolve().as_posix().rstrip("/") + "/"
            self._available_source_uris = None
        else:
            # GDAL/QGIS potrafi czytać SHP i GML bezpośrednio z ZIP przez /vsizip/.
            # Dzięki temu nie tworzymy katalogów tymczasowych i warstwy zachowują
            # poprawne źródło także po zapisaniu projektu QGIS.
            zip_prefix = f"/vsizip/{source_path.resolve().as_posix()}"
            if parent:
                zip_prefix += "/" + parent.strip("/")
            prefix = zip_prefix.rstrip("/") + "/"
            selected_members = {
                prefix + PurePosixPath(r["member"]).name
                for r in records
                if r["parent"] == parent
            }
            self._available_source_uris = selected_members

        selected_records = [
            r
            for r in records
            if r["parent"] == parent
            and r["namespace"] == namespace
            and r["format"] == data_format
        ]

        return {
            "path": prefix,
            "przestrzen_nazw": namespace,
            "formatPliku": data_format,
            "source_type": source_type,
            "source_path": source_path,
            "source_records": selected_records,
        }

    @staticmethod
    def _scan_folder(folder_path):
        """Zwróć rozpoznane pliki BDOT10k znajdujące się bezpośrednio w katalogu."""
        records = []
        for item in folder_path.iterdir():
            if not item.is_file():
                continue
            match = _DATA_FILE_RE.match(item.name)
            if match:
                records.append(
                    {
                        "parent": "",
                        "namespace": match.group(1),
                        "format": match.group(2).lower(),
                        "member": item.name,
                    }
                )
        return records

    @staticmethod
    def _scan_zip(zip_path):
        """Zwróć rozpoznane pliki BDOT10k z ZIP, także z katalogu nadrzędnego w archiwum."""
        records = []
        with zipfile.ZipFile(zip_path, "r") as archive:
            for member in archive.namelist():
                if member.endswith("/"):
                    continue
                pure = PurePosixPath(member)
                match = _DATA_FILE_RE.match(pure.name)
                if match:
                    parent = "" if str(pure.parent) == "." else pure.parent.as_posix()
                    records.append(
                        {
                            "parent": parent,
                            "namespace": match.group(1),
                            "format": match.group(2).lower(),
                            "member": member,
                        }
                    )
        return records

    def _choose_format(self, formats):
        """W przypadku obecności XML i SHP pozwól użytkownikowi wybrać format."""
        if len(formats) == 1:
            return formats[0]
        if not formats:
            return None

        dialog = QMessageBox(self.iface.mainWindow())
        dialog.setWindowTitle("Format danych BDOT10k")
        dialog.setIcon(QMessageBox.Question)
        dialog.setText("Znaleziono jednocześnie dane XML/GML i SHP. Wybierz format do wczytania.")
        xml_button = dialog.addButton("Wczytaj dane GML / XML", QMessageBox.AcceptRole)
        xml_button.setToolTip("Wczytaj dane w formacie GML/XML i zastosuj style kartograficzne wtyczki.")
        shp_button = dialog.addButton("Wczytaj dane SHP", QMessageBox.AcceptRole)
        shp_button.setToolTip("Wczytaj dane w formacie SHP i zastosuj style kartograficzne wtyczki.")
        cancel_button = dialog.addButton("Anuluj", QMessageBox.RejectRole)
        cancel_button.setToolTip("Zamknij okno bez wczytywania danych.")
        dialog.exec_()

        clicked = dialog.clickedButton()
        if clicked is xml_button:
            return "xml"
        if clicked is shp_button:
            return "shp"
        return None

    def _source_exists(self, uri):
        """Sprawdź istnienie pliku zarówno na dysku, jak i wewnątrz ZIP."""
        if self._available_source_uris is not None:
            return uri in self._available_source_uris
        return Path(uri).is_file()

    @staticmethod
    def _table_name_from_record(record):
        """Zwróć nazwę klasy BDOT10k na podstawie nazwy pliku źródłowego."""
        file_name = PurePosixPath(record["member"]).name
        try:
            data_part = file_name.split("__", 1)[1]
            return data_part.rsplit(".", 1)[0]
        except (IndexError, ValueError):
            return Path(file_name).stem

    @staticmethod
    def _default_gpkg_path(source_type, source_path, namespace):
        """Wyznacz domyślną lokalizację wspólnego GeoPackage dla danych XML."""
        file_name = f"{namespace}_BDOT10k.gpkg"
        if source_type == "folder":
            return source_path / file_name
        return source_path.parent / file_name

    @staticmethod
    def _unique_path(path):
        """Zwróć wolną nazwę pliku, dodając numer, gdy plik już istnieje."""
        if not path.exists():
            return path

        counter = 2
        while True:
            candidate = path.with_name(f"{path.stem}_{counter}{path.suffix}")
            if not candidate.exists():
                return candidate
            counter += 1

    def _xml_source_uri(self, path, record):
        """Zbuduj URI XML/GML dla pliku znajdującego się w katalogu albo ZIP."""
        file_name = PurePosixPath(record["member"]).name
        return f"{path}{file_name}"

    @staticmethod
    def _xml_record_has_features(source_type, source_path, record, table_name):
        """Sprawdź awaryjnie, czy XML zawiera obiekty przestrzenne.

        Ta kontrola jest używana wyłącznie wtedy, gdy OGR nie potrafi otworzyć
        pliku albo zwraca 0 obiektów. Nie decyduje już z góry o pominięciu
        poprawnego XML. Rozpoznawany jest zarówno element konkretnej klasy
        BDOT10k, jak i typowe elementy członkowskie GML/WFS.
        """
        table_name_bytes = table_name.encode("utf-8")

        class_tag = re.compile(
            rb"<(?:[A-Za-z_][A-Za-z0-9_.-]*:)?"
            + re.escape(table_name_bytes)
            + rb"(?=[\s/>])",
            re.IGNORECASE,
        )
        member_tag = re.compile(
            rb"<(?:[A-Za-z_][A-Za-z0-9_.-]*:)?(?:featureMember|member)(?=[\s>])",
            re.IGNORECASE,
        )
        any_bdot_tag = re.compile(
            rb"<(?:[A-Za-z_][A-Za-z0-9_.-]*:)?OT_[A-Za-z0-9_]+(?=[\s/>])",
            re.IGNORECASE,
        )

        def stream_has_feature(stream):
            tail = b""
            while True:
                chunk = stream.read(64 * 1024)
                if not chunk:
                    return False

                data = tail + chunk
                if (
                    class_tag.search(data)
                    or member_tag.search(data)
                    or any_bdot_tag.search(data)
                ):
                    return True

                # Zachowujemy końcówkę, ponieważ znacznik może zostać przecięty
                # pomiędzy dwoma blokami odczytu.
                tail = data[-1024:]

        if source_type == "zip":
            with zipfile.ZipFile(source_path, "r") as archive:
                with archive.open(record["member"], "r") as stream:
                    return stream_has_feature(stream)

        xml_path = source_path / PurePosixPath(record["member"]).name
        with xml_path.open("rb") as stream:
            return stream_has_feature(stream)

    def _convert_xml_to_gpkg(
        self,
        path,
        przestrzen_nazw,
        source_type,
        source_path,
        source_records,
        progress=None,
    ):
        """Zapisz wszystkie pliki XML/GML zbioru BDOT10k do jednego GeoPackage.

        Każdy plik źródłowy jest zapisywany jako osobna tabela o nazwie klasy
        BDOT10k (np. ``OT_SKJZ_L``). Po tej operacji dalsze wczytywanie warstw
        odbywa się wyłącznie z utworzonego pliku GPKG.
        """
        xml_records = sorted(
            (r for r in source_records if r["format"] == "xml"),
            key=lambda r: PurePosixPath(r["member"]).name.lower(),
        )
        if not xml_records:
            return None


        gpkg_path = self._default_gpkg_path(
            source_type,
            source_path,
            przestrzen_nazw,
        )
        # Nie nadpisuj wcześniejszego importu. Jeżeli plik o domyślnej nazwie
        # już istnieje, utwórz kolejny, np. *_2.gpkg.
        gpkg_path = self._unique_path(gpkg_path)

        transform_context = QgsProject.instance().transformContext()
        target_crs = QgsCoordinateReferenceSystem("EPSG:2180")
        written_tables = set()

        for index, record in enumerate(xml_records, start=1):
            source_uri = self._xml_source_uri(
                path,
                record,
            )
            table_name = self._table_name_from_record(record)


            if table_name in written_tables:
                continue

            # Najpierw pozwalamy OGR odczytać XML. W pierwszej kolejności
            # wskazujemy jawnie nazwę klasy, ponieważ część plików GML może być
            # prezentowana przez sterownik jako źródło wielowarstwowe. Dopiero
            # gdy OGR nie zwróci obiektów, sprawdzamy treść XML i rozstrzygamy,
            # czy plik jest rzeczywiście pusty.
            source_layer = None
            ogr_candidates = (
                f"{source_uri}|layername={table_name}",
                source_uri,
            )

            for candidate_no, candidate_uri in enumerate(ogr_candidates, start=1):
                candidate_layer = QgsVectorLayer(candidate_uri, table_name, "ogr")
                valid = candidate_layer.isValid()

                if not valid:
                    continue

                try:
                    feature_count = candidate_layer.featureCount()
                except Exception as exc:
                    feature_count = -1

                if feature_count > 0:
                    source_layer = candidate_layer
                    break


            if source_layer is None:
                try:
                    has_features = self._xml_record_has_features(
                        source_type,
                        source_path,
                        record,
                        table_name,
                    )
                except (OSError, KeyError, zipfile.BadZipFile) as exc:
                    try:
                        gpkg_path.unlink(missing_ok=True)
                    except OSError:
                        pass
                    QMessageBox.critical(
                        self.iface.mainWindow(),
                        "BDOT10k",
                        "Nie można odczytać pliku XML/GML podczas sprawdzania "
                        f"zawartości:\n{source_uri}\n\nBłąd: {exc}",
                    )
                    return None

                if not has_features:
                    if progress is not None:
                        self._set_progress(progress, index)
                    continue

                try:
                    gpkg_path.unlink(missing_ok=True)
                except OSError:
                    pass
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "BDOT10k",
                    "Plik XML/GML zawiera obiekty, ale OGR nie potrafi odczytać "
                    f"warstwy {table_name}:\n{source_uri}",
                )
                return None

            options = QgsVectorFileWriter.SaveVectorOptions()
            options.driverName = "GPKG"
            options.fileEncoding = "UTF-8"
            options.layerName = table_name

            # Wymuś zapis wszystkich tabel GeoPackage w układzie PL-1992
            # (EPSG:2180). Jeżeli źródło ma inny poprawny CRS, geometria jest
            # transformowana podczas zapisu. Gdy CRS źródła nie jest określony,
            # dane BDOT10k są interpretowane jako EPSG:2180.
            source_crs = source_layer.crs()
            if not source_crs.isValid():
                source_layer.setCrs(target_crs)
            elif source_crs != target_crs:
                options.ct = QgsCoordinateTransform(
                    source_crs,
                    target_crs,
                    transform_context,
                )

            options.actionOnExistingFile = (
                QgsVectorFileWriter.CreateOrOverwriteFile
                if not written_tables
                else QgsVectorFileWriter.CreateOrOverwriteLayer
            )

            result = QgsVectorFileWriter.writeAsVectorFormatV3(
                source_layer,
                str(gpkg_path),
                transform_context,
                options,
            )
            error = result[0]
            error_message = result[1] if len(result) > 1 else ""
            if error != QgsVectorFileWriter.NoError:
                try:
                    gpkg_path.unlink(missing_ok=True)
                except OSError:
                    pass
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "BDOT10k",
                    "Nie udało się zapisać danych XML/GML do GeoPackage.\n\n"
                    f"Klasa: {table_name}\n"
                    f"Błąd: {error_message or error}",
                )
                return None

            written_tables.add(table_name)

            if progress is not None:
                self._set_progress(progress, index)

        if not written_tables:
            QMessageBox.information(
                self.iface.mainWindow(),
                "BDOT10k",
                "Wszystkie pliki XML/GML są puste. Nie utworzono pliku "
                "GeoPackage ani warstw w projekcie.",
            )
            return None


        if not gpkg_path.is_file():
            QMessageBox.critical(
                self.iface.mainWindow(),
                "BDOT10k",
                "Nie utworzono pliku GeoPackage z danych XML/GML.",
            )
            return None

        return gpkg_path

    def _install_svg_symbols(self):
        """Skopiuj symbole KARTO10k do katalogu SVG profilu QGIS."""
        source = self.plugin_dir / "BDOT10k_SVG" / "KARTO10k"
        destination = Path(QgsApplication.qgisSettingsDirPath()) / "SVG" / "KARTO10k"
        try:
            shutil.copytree(source, destination, dirs_exist_ok=True)
        except OSError as exc:
            QMessageBox.warning(
                self.iface.mainWindow(),
                "BDOT10k",
                f"Nie udało się skopiować symboli KARTO10k:\n{exc}",
            )

    @staticmethod
    def _set_progress(progress, value):
        """Ustaw postęp i pozwól Qt odświeżyć interfejs podczas importu."""
        progress.setValue(value)
        QCoreApplication.processEvents()

    def _add_configured_layer(
        self,
        spec,
        path,
        przestrzen_nazw,
        formatPliku,
        target_group,
        root,
        qml_path,
        gpkg_path=None,
    ):
        """Wczytaj pojedynczą warstwę opisaną w ``LAYER_SPECS``.

        Dla XML/GML źródłem warstwy jest tabela w uprzednio utworzonym
        wspólnym GeoPackage. Dla SHP zachowane jest bezpośrednie wczytywanie
        pliku źródłowego.
        """
        if gpkg_path is not None:
            source_uri = f"{gpkg_path}|layername={spec['source']}"
        else:
            source_uri = f"{path}{przestrzen_nazw}__{spec['source']}.{formatPliku}"
            if not self._source_exists(source_uri):
                return None

        layer = QgsVectorLayer(
            source_uri,
            f"{przestrzen_nazw}__{spec['name']}",
            "ogr",
        )
        valid = layer.isValid()
        if not valid:
            return None

        # Wszystkie warstwy dodawane do projektu QGIS mają jawnie ustawiony
        # układ PL-1992 (EPSG:2180), niezależnie od sposobu ich wczytania.
        layer.setCrs(QgsCoordinateReferenceSystem("EPSG:2180"))

        count_before_filter, has_features_before = self._layer_feature_state(
            layer,
            "przed filtrem: ",
        )
        if not has_features_before:
            return None

        # GML może przechowywać wersje historyczne. Jeżeli pole końca wersji
        # istnieje, prezentujemy wyłącznie obiekty aktualne. Dla klas z dodatkowymi
        # kryteriami konfiguracja zawiera pełny filtr dla obu wariantów schematu.
        if formatPliku == "xml":
            has_end_of_version = layer.fields().indexFromName("koniecWersjiObiektu") != -1
            if "xml_filter_current" in spec:
                subset = (
                    spec["xml_filter_current"]
                    if has_end_of_version
                    else spec["xml_filter_without_current"]
                )
                layer.setSubsetString(subset)
            elif has_end_of_version:
                layer.setSubsetString("koniecWersjiObiektu is null")
        elif formatPliku == "shp" and "shp_filter" in spec:
            layer.setSubsetString(spec["shp_filter"])

        count_after_filter, has_features_after = self._layer_feature_state(
            layer,
            "po filtrze: ",
        )

        # Niektóre warstwy opisowe mają sens tylko wtedy, gdy filtr pozostawił
        # co najmniej jeden obiekt. Zachowuje to zachowanie wcześniejszej wersji.
        if spec.get("require_filtered_features") and not has_features_after:
            return None

        QgsProject.instance().addMapLayer(layer, False)
        target_group.addLayer(layer)
        style_path = qml_path / spec["style"]
        layer.loadNamedStyle(str(style_path))

        layer_node = root.findLayer(layer.id())
        if layer_node is not None:
            layer_node.setExpanded(False)
        return layer

    @staticmethod
    def _brown_road_symbol_layer_references(road_layer):
        """Zwróć referencje do brązowej obwódki jezdni w stylu SKJZ.

        Styl ``OT_SKJZ_L [33-38]`` jest kategoryzowany i dla każdej
        kategorii pierwsza warstwa symbolu stanowi brązową obwódkę jezdni.
        Referencje są budowane w sposób zgodny zarówno z QGIS 3.22, jak i
        z nowszym API identyfikującym warstwy symbolu przez trwałe ID.
        """
        renderer = road_layer.renderer()
        if renderer is None or renderer.type() != "categorizedSymbol":
            return []

        references = []
        for category in renderer.categories():
            symbol = category.symbol()
            if symbol is None or symbol.symbolLayerCount() == 0:
                continue

            symbol_layer = symbol.symbolLayer(0)

            # Od QGIS 3.30 QgsSymbolLayerReference korzysta bezpośrednio
            # z identyfikatora warstwy symbolu. W QGIS 3.22--3.28 wymagany
            # jest starszy QgsSymbolLayerId: wartość kategorii + ścieżka [0].
            try:
                symbol_layer_id = symbol_layer.id()
                references.append(
                    QgsSymbolLayerReference(road_layer.id(), symbol_layer_id)
                )
            except (AttributeError, TypeError):
                references.append(
                    QgsSymbolLayerReference(
                        road_layer.id(),
                        QgsSymbolLayerId(str(category.value()), 0),
                    )
                )

        return references

    def _configure_street_label_mask(self, loaded_layers):
        """Maskuj brązową obwódkę jezdni dokładnie pod nazwami ulic.

        Nazwy ulic nie mają widocznego bufora (halo). Zamiast niego QGIS
        wykorzystuje selektywną maskę etykiety, która wycina wyłącznie
        pierwszą, brązową warstwę symbolu jezdni z poziomów 33--38.
        Pozostałe części symbolizacji drogi pozostają widoczne.
        """
        street_labels = loaded_layers.get("nazwy ulic [65].qml")
        roads = loaded_layers.get("OT_SKJZ_L [33-38].qml")
        if street_labels is None or roads is None:
            return

        references = self._brown_road_symbol_layer_references(roads)
        if not references:
            return

        labeling = street_labels.labeling()
        if labeling is None:
            return

        settings = labeling.settings()
        text_format = settings.format()
        text_format.mask().setEnabled(True)
        text_format.mask().setMaskedSymbolLayers(references)
        settings.setFormat(text_format)
        labeling.setSettings(settings)
        street_labels.triggerRepaint()

    def _load_dataset(
        self,
        path,
        przestrzen_nazw,
        formatPliku,
        source_type,
        source_path,
        source_records,
    ):
        """Wczytaj wszystkie skonfigurowane warstwy BDOT10k do projektu QGIS."""
        teryt = przestrzen_nazw[-4:]
        nazwa_powiatu = POWIATY.get(teryt, f"TERYT {teryt}")
        root = QgsProject.instance().layerTreeRoot()
        group_name = f"BDOT10k POWIAT {nazwa_powiatu}"

        # Ostrzeż użytkownika, gdy ten sam powiat jest już obecny w projekcie.
        # Sprawdzamy zarówno własność zapisywaną przez aktualną wersję wtyczki,
        # jak i nazwę grupy, aby wykryć dane wczytane wcześniejszymi wersjami.
        duplicate_found = False
        for child in root.children():
            try:
                loaded_teryt = str(
                    child.customProperty(
                        "BDOT10k_GML_SHP_Loader/teryt",
                        "",
                    )
                )
            except (AttributeError, TypeError):
                loaded_teryt = ""

            try:
                child_name = child.name()
            except AttributeError:
                child_name = ""

            if loaded_teryt == teryt or child_name == group_name:
                duplicate_found = True
                break

        if duplicate_found:
            duplicate_dialog = QMessageBox(self.iface.mainWindow())
            duplicate_dialog.setWindowTitle("Powiat jest już wczytany")
            duplicate_dialog.setIcon(QMessageBox.Warning)
            duplicate_dialog.setText(
                f"Dane BDOT10k dla powiatu {nazwa_powiatu} (TERYT {teryt}) "
                "są już wczytane do bieżącego projektu.\n\n"
                "Czy chcesz wczytać ten powiat ponownie?"
            )
            load_again_button = duplicate_dialog.addButton(
                "Wczytaj ponownie",
                QMessageBox.AcceptRole,
            )
            load_again_button.setToolTip(
                "Dodaj dane tego samego powiatu do projektu jako kolejną grupę."
            )
            cancel_button = duplicate_dialog.addButton(
                "Anuluj",
                QMessageBox.RejectRole,
            )
            cancel_button.setToolTip(
                "Pozostaw już wczytane dane bez dodawania kolejnej kopii."
            )
            duplicate_dialog.exec_()
            if duplicate_dialog.clickedButton() is not load_again_button:
                return

        qml_path = self.plugin_dir / "BDOT10k_QML"
        self._install_svg_symbols()

        xml_count = (
            len([r for r in source_records if r["format"] == "xml"])
            if formatPliku == "xml"
            else 0
        )
        progress_message = self.iface.messageBar().createMessage("Postęp importowania BDOT10k...")
        progress = QProgressBar()
        progress.setMaximum(87 + xml_count)
        progress.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        progress_message.layout().addWidget(progress)
        self.iface.messageBar().pushWidget(progress_message, Qgis.Info)


        gpkg_path = None
        if formatPliku == "xml":
            gpkg_path = self._convert_xml_to_gpkg(
                path,
                przestrzen_nazw,
                source_type,
                source_path,
                source_records,
                progress=progress,
            )
            if gpkg_path is None:
                self.iface.messageBar().clearWidgets()
                return

        progress_offset = xml_count if gpkg_path is not None else 0

        group = root.addGroup(group_name)
        group.setCustomProperty("BDOT10k_GML_SHP_Loader/teryt", teryt)
        if gpkg_path is not None:
            group.setCustomProperty(
                "BDOT10k_GML_SHP_Loader/gpkg_path",
                str(gpkg_path),
            )
        group.setExpanded(False)
        group_napisy = group.addGroup(f"{przestrzen_nazw} napisy")
        group_napisy.setExpanded(False)

        try:
            current_progress = None
            loaded_layers = {}
            for spec in LAYER_SPECS:
                if current_progress is not None and spec["progress"] != current_progress:
                    self._set_progress(progress, progress_offset + current_progress)

                target_group = group_napisy if spec["target"] == "labels" else group
                layer = self._add_configured_layer(
                    spec,
                    path,
                    przestrzen_nazw,
                    formatPliku,
                    target_group,
                    root,
                    qml_path,
                    gpkg_path=gpkg_path,
                )
                if layer is not None:
                    loaded_layers[spec["style"]] = layer
                current_progress = spec["progress"]


            # Selektywne maskowanie wymaga identyfikatorów rzeczywiście
            # utworzonych warstw QGIS, dlatego konfigurujemy je po imporcie.
            self._configure_street_label_mask(loaded_layers)

            if current_progress is not None:
                self._set_progress(progress, progress_offset + current_progress)
        finally:
            self.iface.messageBar().clearWidgets()

        if gpkg_path is not None:
            self.iface.messageBar().pushSuccess(
                "BDOT10k",
                f"Dane XML zapisano do GeoPackage i wczytano z pliku: {gpkg_path}",
            )
