"""
/***************************************************************************
 BDOT10k_GML_SHP_Loader
                                 A QGIS plugin
 Importuje BDOT10k w formacie GML albo SHP
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Marcin Lebiecki / Główny Urząd Geodezji i Kartografii
        email                : marcin.lebiecki@gugik.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
"""Obsługa pobierania powiatowych paczek BDOT10k z Geoportalu GUGiK."""

from pathlib import Path

from qgis.PyQt.QtCore import (
    QEventLoop,
    QSettings,
    QSortFilterProxyModel,
    Qt,
    QUrl,
)
from qgis.PyQt.QtWidgets import (
    QComboBox,
    QCompleter,
    QDialog,
    QDialogButtonBox,
    QFileDialog,
    QFormLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QProgressDialog,
    QPushButton,
    QVBoxLayout,
    QWidget,
)
from qgis.core import QgsFileDownloader

from .constants import POWIATY


GEOPORTAL_BASE_URL = "https://opendata.geoportal.gov.pl/bdot10k/schemat2021"
_SETTINGS_GROUP = "BDOT10k_GML_SHP_Loader"


class GeoportalDownloadDialog(QDialog):
    """Okno wyboru powiatu i katalogu zapisu danych z Geoportalu."""

    _POLISH_TRANSLATION = str.maketrans(
        "ąćęłńóśźżĄĆĘŁŃÓŚŹŻ",
        "acelnoszzACELNOSZZ",
    )

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Pobierz BDOT10k z Geoportalu")
        self.resize(650, 155)

        settings = QSettings()
        # Nie podpowiadamy automatycznie systemowego katalogu Pobrane.
        # Przycisk pobierania ma być aktywny dopiero wtedy, gdy użytkownik
        # wskaże katalog (lub wcześniej zapamiętany katalog nadal istnieje).
        default_dir = str(
            settings.value(f"{_SETTINGS_GROUP}/lastDownloadDir", "")
        )
        last_teryt = str(settings.value(f"{_SETTINGS_GROUP}/lastGeoportalTeryt", ""))

        # Edytowalny QComboBox pełni jednocześnie rolę wyszukiwarki i listy.
        # Lista QComboBox pozostaje stała podczas wpisywania. Wyniki wyszukiwania
        # są wyświetlane przez osobny QCompleter, dzięki czemu wpisanie kolejnych
        # znaków nie przebudowuje modelu i nie resetuje kursora w edytorze.
        self.powiat_combo = QComboBox(self)
        self.powiat_combo.setEditable(True)
        self.powiat_combo.setInsertPolicy(QComboBox.NoInsert)
        self.powiat_combo.setMinimumWidth(430)
        self.powiat_combo.lineEdit().setPlaceholderText(
            "Wpisz fragment nazwy powiatu lub kod TERYT"
        )
        self.powiat_combo.lineEdit().setClearButtonEnabled(True)
        powiat_tooltip = (
            "Wybierz powiat z listy albo wpisz fragment jego nazwy, np. „lesz” lub „warsz”. "
            "Możesz również wpisać pełny albo częściowy kod TERYT powiatu, np. „1004”. "
            "Wyszukiwanie nie rozróżnia wielkości liter ani polskich znaków."
        )
        self.powiat_combo.setToolTip(powiat_tooltip)
        self.powiat_combo.lineEdit().setToolTip(powiat_tooltip)

        self.destination_edit = QLineEdit(default_dir, self)
        self.destination_edit.setToolTip(
            "Katalog, w którym zostanie zapisany pobrany plik ZIP z danymi BDOT10k."
        )
        browse_button = QPushButton("Wybierz katalog…", self)
        browse_button.setToolTip(
            "Wskaż katalog, do którego ma zostać zapisany pobrany plik ZIP z Geoportalu."
        )
        browse_button.clicked.connect(self._select_destination)

        destination_widget = QWidget(self)
        destination_layout = QHBoxLayout(destination_widget)
        destination_layout.setContentsMargins(0, 0, 0, 0)
        destination_layout.addWidget(self.destination_edit, 1)
        destination_layout.addWidget(browse_button)

        form = QFormLayout()
        form.addRow("Powiat:", self.powiat_combo)
        form.addRow("Katalog zapisu:", destination_widget)

        info = QLabel(
            "Wybierz powiat z listy albo wpisz fragment jego nazwy lub kod TERYT. "
            "Po pobraniu plik ZIP zostanie zapisany we wskazanym katalogu i automatycznie wczytany do QGIS.",
            self,
        )
        info.setWordWrap(True)

        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel, self)
        self.download_button = buttons.button(QDialogButtonBox.Ok)
        self.download_button.setText("Pobierz i wczytaj dane")
        self.download_button.setToolTip(
            "Pobierz paczkę BDOT10k dla wybranego powiatu, zapisz ją w podanym katalogu i wczytaj do QGIS."
        )
        cancel_button = buttons.button(QDialogButtonBox.Cancel)
        cancel_button.setText("Anuluj")
        cancel_button.setToolTip("Zamknij okno bez pobierania danych.")
        buttons.accepted.connect(self._accept_if_valid)
        buttons.rejected.connect(self.reject)

        layout = QVBoxLayout(self)
        layout.addWidget(info)
        layout.addLayout(form)
        layout.addWidget(buttons)

        self._populate_powiaty()
        self._setup_completer()

        # Stan przycisku jest zawsze zależny od obu wymaganych danych:
        # jednoznacznie wskazanego powiatu oraz istniejącego katalogu zapisu.
        self.powiat_combo.currentIndexChanged.connect(self._update_download_button_state)
        self.powiat_combo.lineEdit().textChanged.connect(self._update_download_button_state)
        self.destination_edit.textChanged.connect(self._update_download_button_state)

        if last_teryt:
            index = self.powiat_combo.findData(last_teryt)
            if index >= 0:
                self.powiat_combo.setCurrentIndex(index)
            else:
                self.powiat_combo.setCurrentIndex(-1)
                self.powiat_combo.lineEdit().clear()
        else:
            self.powiat_combo.setCurrentIndex(-1)
            self.powiat_combo.lineEdit().clear()

        self._update_download_button_state()

    @classmethod
    def _normalize(cls, text):
        """Ujednolić tekst wyszukiwania, ignorując wielkość liter i polskie znaki."""
        return str(text).translate(cls._POLISH_TRANSLATION).casefold().strip()

    def _matching_powiaty(self, text):
        """Zwróć powiaty pasujące do fragmentu nazwy lub kodu TERYT."""
        phrase = self._normalize(text)
        return [
            (teryt, name)
            for teryt, name in sorted(POWIATY.items(), key=lambda item: (item[1], item[0]))
            if not phrase
            or phrase in self._normalize(name)
            or phrase in teryt
        ]

    def _populate_powiaty(self):
        """Wypełnij QComboBox pełną, niezmienną listą powiatów."""
        for teryt, name in self._matching_powiaty(""):
            self.powiat_combo.addItem(f"{name} — {teryt}", teryt)
            index = self.powiat_combo.count() - 1
            # Osobna rola zawiera znormalizowaną nazwę i TERYT. Proxy filtruje
            # właśnie po niej, więc wyszukiwanie działa także bez polskich znaków.
            search_key = self._normalize(f"{name} {teryt}")
            self.powiat_combo.setItemData(index, search_key, Qt.UserRole + 1)

    def _setup_completer(self):
        """Skonfiguruj podpowiedzi bez przebudowywania modelu QComboBox."""
        self._powiat_proxy = QSortFilterProxyModel(self)
        self._powiat_proxy.setSourceModel(self.powiat_combo.model())
        self._powiat_proxy.setFilterRole(Qt.UserRole + 1)
        self._powiat_proxy.setFilterKeyColumn(0)
        self._powiat_proxy.setFilterCaseSensitivity(Qt.CaseInsensitive)

        self._powiat_completer = QCompleter(self._powiat_proxy, self)
        # Wyniki są już odfiltrowane w proxy. Tryb UnfilteredPopupCompletion
        # zapobiega ponownemu filtrowaniu przez QCompleter po oryginalnym tekście
        # (ważne np. przy wpisywaniu nazw bez polskich znaków).
        self._powiat_completer.setCompletionMode(QCompleter.UnfilteredPopupCompletion)
        self._powiat_completer.setCaseSensitivity(Qt.CaseInsensitive)
        self._powiat_completer.setMaxVisibleItems(15)
        self.powiat_combo.setCompleter(self._powiat_completer)

        self.powiat_combo.lineEdit().textEdited.connect(self._update_completer)
        self._powiat_completer.activated[str].connect(self._select_completion)

    def _update_completer(self, text):
        """Aktualizuj listę podpowiedzi, nie zmieniając tekstu edytora."""
        phrase = text.split(" — ", 1)[0] if " — " in text else text
        normalized = self._normalize(phrase)
        self._powiat_proxy.setFilterFixedString(normalized)

        if normalized and self._powiat_proxy.rowCount() > 0:
            self._powiat_completer.complete()
        else:
            self._powiat_completer.popup().hide()

    def _select_completion(self, text):
        """Przenieś wybór z listy podpowiedzi do właściwego QComboBox."""
        index = self.powiat_combo.findText(text, Qt.MatchExactly)
        if index < 0:
            return

        self.powiat_combo.setCurrentIndex(index)
        self.powiat_combo.lineEdit().setCursorPosition(
            len(self.powiat_combo.currentText())
        )


    def _update_download_button_state(self, *args):
        """Włącz pobieranie dopiero po wskazaniu powiatu i katalogu zapisu."""
        has_powiat = bool(self.selected_teryt())
        destination_text = self.destination_edit.text().strip()
        has_directory = bool(destination_text) and self.destination_directory().is_dir()
        self.download_button.setEnabled(has_powiat and has_directory)

    @staticmethod
    def build_url(teryt):
        """Zbuduj adres powiatowej paczki GML na podstawie kodu TERYT."""
        return f"{GEOPORTAL_BASE_URL}/{teryt[:2]}/{teryt}_GML.zip"

    def selected_teryt(self):
        """Zwróć kod TERYT wybranego powiatu albo jednoznacznego wyniku."""
        text = self.powiat_combo.currentText().strip()
        index = self.powiat_combo.currentIndex()

        # currentIndex może wskazywać poprzednią pozycję także wtedy, gdy
        # użytkownik zaczął wpisywać nową frazę. Uznajemy pozycję za wybraną
        # tylko wtedy, gdy tekst edytora dokładnie odpowiada pozycji z listy.
        if index >= 0 and text == self.powiat_combo.itemText(index):
            data = self.powiat_combo.itemData(index)
            return str(data) if data else ""

        matches = self._matching_powiaty(text)
        if len(matches) == 1:
            return matches[0][0]
        return ""

    def destination_directory(self):
        """Zwróć katalog wskazany jako miejsce zapisu pobranej paczki."""
        return Path(self.destination_edit.text().strip()).expanduser()

    def _select_destination(self):
        """Wskaż katalog, w którym ma zostać zapisany pobrany plik ZIP."""
        start_dir = self.destination_edit.text().strip()
        directory = QFileDialog.getExistingDirectory(
            self,
            "Wybierz katalog zapisu danych BDOT10k",
            start_dir,
        )
        if directory:
            self.destination_edit.setText(directory)

    def _accept_if_valid(self):
        """Sprawdź wybór powiatu i katalogu przed rozpoczęciem pobierania."""
        teryt = self.selected_teryt()
        if not teryt:
            matches = self._matching_powiaty(self.powiat_combo.currentText())
            if not matches:
                message = "Nie znaleziono powiatu pasującego do wpisanej nazwy lub kodu TERYT."
            else:
                message = "Wybierz właściwy powiat z listy podpowiedzi."
            QMessageBox.warning(self, "BDOT10k", message)
            return

        directory = self.destination_directory()
        if not directory.is_dir():
            QMessageBox.warning(
                self,
                "BDOT10k",
                "Wskazany katalog zapisu nie istnieje.",
            )
            return

        settings = QSettings()
        settings.setValue(f"{_SETTINGS_GROUP}/lastGeoportalTeryt", teryt)
        settings.setValue(f"{_SETTINGS_GROUP}/lastDownloadDir", str(directory))
        self.accept()


def _ask_existing_file(parent, target_path):
    """Zapytaj, czy zastąpić istniejącą paczkę, czy użyć jej bez pobierania."""
    dialog = QMessageBox(parent)
    dialog.setWindowTitle("Plik BDOT10k już istnieje")
    dialog.setIcon(QMessageBox.Question)
    dialog.setText(
        "W wybranym katalogu znajduje się już paczka danych dla tego powiatu.\n\n"
        f"{target_path.name}"
    )
    replace_button = dialog.addButton("Pobierz ponownie i zastąp plik", QMessageBox.AcceptRole)
    replace_button.setToolTip(
        "Pobierz aktualną paczkę z Geoportalu i zastąp istniejący plik ZIP."
    )
    use_button = dialog.addButton("Użyj istniejącego pliku", QMessageBox.ActionRole)
    use_button.setToolTip(
        "Nie pobieraj danych ponownie. Użyj istniejącego pliku ZIP i wczytaj go do QGIS."
    )
    cancel_button = dialog.addButton("Anuluj", QMessageBox.RejectRole)
    cancel_button.setToolTip("Przerwij operację bez pobierania i bez wczytywania danych.")
    dialog.exec_()

    clicked = dialog.clickedButton()
    if clicked is replace_button:
        return "replace"
    if clicked is use_button:
        return "use"
    return "cancel"


def download_geoportal_zip(parent, teryt, destination_directory):
    """Pobierz paczkę BDOT10k z Geoportalu i zwróć ścieżkę do pliku ZIP.

    Do pobierania wykorzystywany jest ``QgsFileDownloader`` z biblioteki QGIS.
    Klasa ta zapisuje dane bezpośrednio do pliku, korzysta z konfiguracji sieciowej
    QGIS i obsługuje przekierowania HTTP. Pobranie wykonywane jest najpierw do
    pliku ``.part``; dopiero poprawne archiwum ZIP zastępuje plik docelowy.
    """
    import zipfile

    destination_directory = Path(destination_directory).expanduser()
    target_path = destination_directory / f"{teryt}_GML.zip"

    if not destination_directory.is_dir():
        QMessageBox.critical(
            parent,
            "BDOT10k",
            "Wskazany katalog zapisu nie istnieje.",
        )
        return None

    if target_path.exists():
        existing_action = _ask_existing_file(parent, target_path)
        if existing_action == "use":
            if zipfile.is_zipfile(target_path):
                return target_path
            QMessageBox.critical(
                parent,
                "BDOT10k",
                "Istniejący plik nie jest poprawnym archiwum ZIP. Wybierz ponowne pobranie danych.",
            )
            return None
        if existing_action == "cancel":
            return None

    temporary_path = target_path.with_suffix(target_path.suffix + ".part")
    try:
        if temporary_path.exists():
            temporary_path.unlink()
    except OSError as exc:
        QMessageBox.critical(
            parent,
            "BDOT10k",
            f"Nie można przygotować pliku tymczasowego do pobierania:\n{exc}",
        )
        return None

    url = GeoportalDownloadDialog.build_url(teryt)
    progress = QProgressDialog(
        f"Pobieranie danych BDOT10k dla TERYT {teryt}…",
        "Anuluj pobieranie",
        0,
        100,
        parent,
    )
    progress.setWindowTitle("Pobieranie danych BDOT10k")
    progress.setWindowModality(Qt.WindowModal)
    progress.setMinimumDuration(0)
    progress.setAutoClose(False)
    progress.setAutoReset(False)
    progress.setToolTip(
        "Dane są pobierane z Geoportalu i zapisywane bezpośrednio we wskazanym katalogu."
    )
    progress.show()

    cancel_button = progress.findChild(QPushButton)
    if cancel_button is not None:
        cancel_button.setToolTip("Przerwij pobieranie danych i usuń niekompletny plik.")

    state = {
        "completed": False,
        "canceled": False,
        "errors": [],
    }

    # delayStart=True pozwala podłączyć wszystkie sygnały zanim rozpocznie się
    # pobieranie. Jest to ważne także dla bardzo małych odpowiedzi HTTP.
    downloader = QgsFileDownloader(
        QUrl(url),
        str(temporary_path),
        "",
        True,
    )

    def update_progress(received, total):
        if total > 0:
            progress.setRange(0, 100)
            progress.setValue(min(100, int(received * 100 / total)))
            progress.setLabelText(
                "Pobieranie danych BDOT10k…\n"
                f"{received / (1024 * 1024):.1f} MB z {total / (1024 * 1024):.1f} MB"
            )
        else:
            progress.setRange(0, 0)
            progress.setLabelText(
                "Pobieranie danych BDOT10k…\n"
                f"Pobrano {received / (1024 * 1024):.1f} MB"
            )

    def mark_completed(_url):
        state["completed"] = True

    def mark_canceled():
        state["canceled"] = True

    def mark_error(messages):
        state["errors"].extend(str(message) for message in messages)

    loop = QEventLoop()
    downloader.downloadProgress.connect(update_progress)
    downloader.downloadCompleted.connect(mark_completed)
    downloader.downloadCanceled.connect(mark_canceled)
    downloader.downloadError.connect(mark_error)
    downloader.downloadExited.connect(loop.quit)
    progress.canceled.connect(downloader.cancelDownload)

    downloader.startDownload()
    loop.exec_()

    # Najpierw odłącz anulowanie, żeby zamknięcie okna po poprawnym pobraniu
    # nie uruchomiło już cancelDownload().
    try:
        progress.canceled.disconnect(downloader.cancelDownload)
    except (TypeError, RuntimeError):
        pass
    progress.close()

    if state["canceled"]:
        try:
            temporary_path.unlink()
        except OSError:
            pass
        return None

    if state["errors"] or not state["completed"]:
        try:
            temporary_path.unlink()
        except OSError:
            pass
        details = "\n".join(state["errors"]) if state["errors"] else "Pobieranie nie zostało zakończone poprawnie."
        QMessageBox.critical(
            parent,
            "BDOT10k",
            "Nie udało się pobrać danych z Geoportalu.\n\n" + details,
        )
        return None

    if not temporary_path.is_file() or temporary_path.stat().st_size == 0:
        try:
            temporary_path.unlink()
        except OSError:
            pass
        QMessageBox.critical(
            parent,
            "BDOT10k",
            "Pobieranie zakończyło się bez zapisania danych do pliku.",
        )
        return None

    if not zipfile.is_zipfile(temporary_path):
        try:
            temporary_path.unlink()
        except OSError:
            pass
        QMessageBox.critical(
            parent,
            "BDOT10k",
            "Geoportal nie zwrócił poprawnego archiwum ZIP dla wybranego powiatu.",
        )
        return None

    try:
        temporary_path.replace(target_path)
    except OSError as exc:
        try:
            temporary_path.unlink()
        except OSError:
            pass
        QMessageBox.critical(
            parent,
            "BDOT10k",
            f"Pobrano dane, ale nie można zapisać pliku docelowego:\n{exc}",
        )
        return None

    return target_path
