"""
/***************************************************************************
 BDOT10k_GML_SHP_Loader
                                 A QGIS plugin
 Importuje BDOT10k w formacie GML albo SHP
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-04
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Marcin Lebiecki / Główny Urząd Geodezji i Kartografii
        email                : marcin.lebiecki@gugik.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
"""Narzędzia pomocnicze dostępne z menu „Pomoc” wtyczki BDOT10k."""

from pathlib import Path

from qgis.PyQt.QtCore import QEventLoop, Qt, QUrl
from qgis.PyQt.QtGui import QDesktopServices, QPixmap
from qgis.PyQt.QtNetwork import QNetworkReply, QNetworkRequest
from qgis.PyQt.QtWidgets import (
    QDialog,
    QDialogButtonBox,
    QFileDialog,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QLabel,
    QMessageBox,
    QProgressDialog,
    QVBoxLayout,
)
from qgis.PyQt.QtXml import QDomDocument
from qgis.core import (
    QgsApplication,
    QgsFileDownloader,
    QgsNetworkAccessManager,
    QgsProject,
    QgsRasterLayer,
)


# Oficjalny tekst rozporządzenia w systemie ELI (Dz.U. 2021 poz. 1412).
BDOT10K_REGULATION_PDF_URL = "https://eli.gov.pl/api/acts/DU/2021/1412/text.pdf"
BDOT10K_REGULATION_FILENAME = "Rozporzadzenie_BDOT10k_DzU_2021_poz_1412.pdf"

# Usługa GUGiK prezentująca monitoring pozyskiwania danych BDOT10k.
BDOT10K_MONITORING_WMS_URL = (
    "https://mapy.geoportal.gov.pl/wss/service/pub/guest/"
    "Stan_BDOT10k/MapServer/WMSServer"
)
BDOT10K_MONITORING_GROUP_NAME = "Monitoring pozyskiwania BDOT10k"

# Usługa GUGiK prezentująca skorowidze / aktualność danych BDOT10k.
BDOT10K_CURRENTNESS_WMS_URL = (
    "https://mapy.geoportal.gov.pl/wss/service/pub/guest/"
    "Skorowidze_BDOT10k/MapServer/WMSServer"
)
BDOT10K_CURRENTNESS_GROUP_NAME = "Aktualność BDOT10k"


def download_bdot10k_regulation(parent):
    """Pobierz oficjalny PDF rozporządzenia BDOT10k do pliku wskazanego przez użytkownika."""
    default_directory = Path.home() / "Downloads"
    if not default_directory.is_dir():
        default_directory = Path.home()

    target_name, _ = QFileDialog.getSaveFileName(
        parent,
        "Zapisz rozporządzenie BDOT10k",
        str(default_directory / BDOT10K_REGULATION_FILENAME),
        "Dokument PDF (*.pdf)",
    )
    if not target_name:
        return

    target_path = Path(target_name)
    if target_path.suffix.lower() != ".pdf":
        target_path = target_path.with_suffix(".pdf")

    temporary_path = target_path.with_suffix(target_path.suffix + ".part")
    try:
        if temporary_path.exists():
            temporary_path.unlink()
    except OSError as exc:
        QMessageBox.critical(
            parent,
            "BDOT10k",
            f"Nie można przygotować pliku do pobrania rozporządzenia:\n{exc}",
        )
        return

    progress = QProgressDialog(
        "Pobieranie rozporządzenia BDOT10k…",
        "Anuluj pobieranie",
        0,
        100,
        parent,
    )
    progress.setWindowTitle("Pobieranie rozporządzenia BDOT10k")
    progress.setMinimumDuration(0)
    progress.setAutoClose(False)
    progress.setAutoReset(False)
    progress.show()

    state = {"completed": False, "canceled": False, "errors": []}
    downloader = QgsFileDownloader(
        QUrl(BDOT10K_REGULATION_PDF_URL),
        str(temporary_path),
        "",
        True,
    )

    def update_progress(received, total):
        if total > 0:
            progress.setRange(0, 100)
            progress.setValue(min(100, int(received * 100 / total)))
        else:
            progress.setRange(0, 0)

    def mark_completed(_url):
        state["completed"] = True

    def mark_canceled():
        state["canceled"] = True

    def mark_error(messages):
        state["errors"].extend(str(message) for message in messages)

    loop = QEventLoop()
    downloader.downloadProgress.connect(update_progress)
    downloader.downloadCompleted.connect(mark_completed)
    downloader.downloadCanceled.connect(mark_canceled)
    downloader.downloadError.connect(mark_error)
    downloader.downloadExited.connect(loop.quit)
    progress.canceled.connect(downloader.cancelDownload)

    downloader.startDownload()
    loop.exec_()

    try:
        progress.canceled.disconnect(downloader.cancelDownload)
    except (TypeError, RuntimeError):
        pass
    progress.close()

    if state["canceled"]:
        _safe_unlink(temporary_path)
        return

    if state["errors"] or not state["completed"]:
        _safe_unlink(temporary_path)
        details = "\n".join(state["errors"]) if state["errors"] else "Pobieranie nie zostało zakończone poprawnie."
        QMessageBox.critical(
            parent,
            "BDOT10k",
            "Nie udało się pobrać rozporządzenia.\n\n" + details,
        )
        return

    try:
        if not temporary_path.is_file() or temporary_path.stat().st_size < 5:
            raise OSError("Pobrany plik jest pusty.")
        with temporary_path.open("rb") as pdf_file:
            if pdf_file.read(5) != b"%PDF-":
                raise OSError("Pobrany plik nie jest dokumentem PDF.")
        temporary_path.replace(target_path)
    except OSError as exc:
        _safe_unlink(temporary_path)
        QMessageBox.critical(
            parent,
            "BDOT10k",
            f"Nie można zapisać pobranego rozporządzenia:\n{exc}",
        )
        return

    # Otwórz pobrany dokument w domyślnej aplikacji systemowej do obsługi PDF.
    # Na większości stanowisk będzie to domyślna przeglądarka PDF lub przeglądarka WWW.
    if not QDesktopServices.openUrl(QUrl.fromLocalFile(str(target_path))):
        QMessageBox.information(
            parent,
            "BDOT10k",
            f"Rozporządzenie zostało zapisane w pliku:\n{target_path}\n\n"
            "Nie udało się otworzyć pliku automatycznie.",
        )


def show_about_dialog(parent, plugin_dir, close_all_callback=None):
    """Wyświetl okno „Informacje” wzorowane na układzie Walidatora plików GML."""
    plugin_dir = Path(plugin_dir)
    metadata = _read_plugin_metadata(plugin_dir / "metadata.txt")

    plugin_name = metadata.get("name", "BDOT10k_GML_SHP")
    version = metadata.get("version", "")
    repository = metadata.get(
        "repository",
        "https://github.com/GlownyUrzadGeodezjiIKartografii/BDOT10k_GML_SHP",
    )
    tracker = metadata.get(
        "tracker",
        repository.rstrip("/") + "/issues",
    )
    documentation = metadata.get(
        "homepage",
        repository,
    ).rstrip("/") + "#readme"

    dialog = QDialog(parent)
    dialog.setProperty("BDOT10k_GML_SHP_Loader_window", True)
    dialog.setWindowTitle("Informacje")
    dialog.setModal(True)
    dialog.resize(600, 450)
    dialog.setMinimumSize(560, 420)

    # Układ celowo nawiązuje do zakładki „Informacje” z Walidatora plików GML:
    # duże pole z parametrami w dwóch kolumnach, logo w lewym dolnym rogu
    # i przyciski Zamknij / Wróć po prawej.
    main_layout = QVBoxLayout(dialog)
    main_layout.setContentsMargins(0, 0, 0, 0)
    main_layout.setSpacing(0)

    info_frame = QFrame(dialog)
    info_frame.setFrameShape(QFrame.StyledPanel)
    info_frame.setFrameShadow(QFrame.Sunken)
    info_frame.setStyleSheet("QFrame { background: white; }")
    info_layout = QGridLayout(info_frame)
    info_layout.setContentsMargins(80, 36, 34, 32)
    info_layout.setHorizontalSpacing(42)
    info_layout.setVerticalSpacing(24)
    info_layout.setColumnMinimumWidth(0, 145)
    info_layout.setColumnStretch(1, 1)

    def add_value_row(row, label_text, value_text, href=None):
        label = QLabel(label_text, info_frame)
        label.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        info_layout.addWidget(label, row, 0)

        value = QLabel(info_frame)
        if href:
            value.setText(f"<a href='{href}'>{value_text}</a>")
            value.setTextFormat(Qt.RichText)
            value.setOpenExternalLinks(True)
            value.setTextInteractionFlags(Qt.TextBrowserInteraction)
        else:
            value.setText(value_text)
        value.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        info_layout.addWidget(value, row, 1)

    add_value_row(0, "Nazwa wtyczki:", plugin_name)
    add_value_row(1, "Wersja wtyczki:", version)
    add_value_row(2, "Repozytorium kodu:", "github", repository)
    add_value_row(3, "Zgłaszanie błędów:", "zgłoś błąd", tracker)
    add_value_row(
        4,
        "Dokumentacja użytkownika:",
        "Pobierz dokumentację użytkownika",
        documentation,
    )
    add_value_row(
        5,
        "Licencja:",
        "GNU GPL v3.0",
        "https://www.gnu.org/licenses/gpl-3.0.html",
    )
    add_value_row(6, "Właściciel:", "GUGiK")

    main_layout.addWidget(info_frame, 1)

    bottom_frame = QFrame(dialog)
    bottom_layout = QHBoxLayout(bottom_frame)
    bottom_layout.setContentsMargins(0, 8, 4, 6)
    bottom_layout.setSpacing(10)

    branding_layout = QVBoxLayout()
    # Niewielki lewy margines przesuwa blok identyfikacji GUGiK w prawo.
    branding_layout.setContentsMargins(16, 0, 0, 0)
    branding_layout.setSpacing(3)

    logo_label = QLabel(bottom_frame)
    logo_path = plugin_dir / "gugik_logo.png"
    if logo_path.is_file():
        logo_pixmap = QPixmap(str(logo_path))
        if not logo_pixmap.isNull():
            logo_label.setPixmap(
                logo_pixmap.scaled(
                    118,
                    68,
                    Qt.KeepAspectRatio,
                    Qt.SmoothTransformation,
                )
            )
    logo_label.setFixedSize(120, 70)
    logo_label.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
    branding_layout.addWidget(logo_label)

    gugik_link = QLabel(
        "<a href='https://www.gov.pl/web/gugik'>GUGiK 2026</a>",
        bottom_frame,
    )
    gugik_link.setTextFormat(Qt.RichText)
    gugik_link.setOpenExternalLinks(True)
    gugik_link.setTextInteractionFlags(Qt.TextBrowserInteraction)
    # Rok i nazwa urzędu są wyśrodkowane dokładnie pod szerokością logo.
    gugik_link.setFixedWidth(120)
    gugik_link.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
    branding_layout.addWidget(gugik_link)

    bottom_layout.addLayout(branding_layout)
    bottom_layout.addStretch(1)

    buttons = QDialogButtonBox(
        QDialogButtonBox.Ok | QDialogButtonBox.Cancel,
        Qt.Horizontal,
        bottom_frame,
    )
    ok_button = buttons.button(QDialogButtonBox.Ok)
    cancel_button = buttons.button(QDialogButtonBox.Cancel)
    if ok_button is not None:
        ok_button.setText("Zamknij")
        ok_button.setToolTip("Zamknij wszystkie okna wtyczki.")
    if cancel_button is not None:
        cancel_button.setText("Wróć")
        cancel_button.setToolTip("Wróć do poprzedniego okna.")
    if close_all_callback is None:
        buttons.accepted.connect(dialog.accept)
    else:
        buttons.accepted.connect(close_all_callback)
    buttons.rejected.connect(dialog.reject)
    bottom_layout.addWidget(buttons, 0, Qt.AlignBottom | Qt.AlignRight)

    main_layout.addWidget(bottom_frame)
    dialog.exec_()


def _read_plugin_metadata(metadata_path):
    """Odczytaj podstawowe pola z sekcji [general] pliku metadata.txt."""
    values = {}
    try:
        for raw_line in metadata_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith(('#', ';', '[')) or '=' not in line:
                continue
            key, value = line.split('=', 1)
            values[key.strip()] = value.strip()
    except OSError:
        pass
    return values


def show_bdot10k_monitoring_wms(parent, iface):
    """Dodaj do projektu WMS prezentujący monitoring pozyskiwania BDOT10k."""
    _show_bdot10k_wms(
        parent,
        iface,
        BDOT10K_MONITORING_WMS_URL,
        BDOT10K_MONITORING_GROUP_NAME,
        "Monitoring pozyskiwania BDOT10k",
    )


def show_bdot10k_currentness_wms(parent, iface):
    """Dodaj do projektu WMS prezentujący aktualność / skorowidze BDOT10k."""
    _show_bdot10k_wms(
        parent,
        iface,
        BDOT10K_CURRENTNESS_WMS_URL,
        BDOT10K_CURRENTNESS_GROUP_NAME,
        "Aktualność BDOT10k",
    )


def _show_bdot10k_wms(parent, iface, service_url, group_name, display_name):
    """Pobierz GetCapabilities wskazanej usługi i dodaj jej warstwy do projektu QGIS."""
    project = QgsProject.instance()

    existing_layers = [
        layer
        for layer in project.mapLayers().values()
        if layer.providerType() == "wms" and service_url in layer.source()
    ]
    if existing_layers:
        for layer in existing_layers:
            node = project.layerTreeRoot().findLayer(layer.id())
            if node is not None:
                node.setItemVisibilityChecked(True)
        iface.messageBar().pushInfo(
            "BDOT10k",
            f"Mapa „{display_name}” jest już dodana do projektu.",
        )
        return

    progress = QProgressDialog(
        "Pobieranie informacji o usłudze WMS…",
        "Anuluj",
        0,
        0,
        parent,
    )
    progress.setWindowTitle(display_name)
    progress.setMinimumDuration(0)
    progress.setAutoClose(False)
    progress.show()

    capabilities_url = service_url + "?SERVICE=WMS&REQUEST=GetCapabilities"
    request = QNetworkRequest(QUrl(capabilities_url))

    # W nowszych wersjach Qt jawnie zezwalamy na bezpieczne przekierowania.
    try:
        request.setAttribute(
            QNetworkRequest.RedirectPolicyAttribute,
            QNetworkRequest.NoLessSafeRedirectPolicy,
        )
    except AttributeError:
        try:
            request.setAttribute(QNetworkRequest.FollowRedirectsAttribute, True)
        except AttributeError:
            pass

    reply = QgsNetworkAccessManager.instance().get(request)
    loop = QEventLoop()
    reply.finished.connect(loop.quit)
    progress.canceled.connect(reply.abort)
    loop.exec_()
    progress.close()

    if reply.error() != QNetworkReply.NoError:
        error_text = reply.errorString()
        reply.deleteLater()
        if error_text.lower() == "operation canceled":
            return
        QMessageBox.critical(
            parent,
            "BDOT10k",
            f"Nie udało się odczytać usługi „{display_name}”.\n\n{error_text}",
        )
        return

    capabilities = bytes(reply.readAll())
    reply.deleteLater()

    layer_specs = _parse_wms_capabilities(capabilities, project.crs().authid())
    if not layer_specs:
        QMessageBox.critical(
            parent,
            "BDOT10k",
            "Usługa WMS nie zwróciła żadnej warstwy możliwej do wyświetlenia.",
        )
        return

    root = project.layerTreeRoot()
    group = root.findGroup(group_name)
    if group is None:
        group = root.insertGroup(0, group_name)

    added_layers = []
    failed_titles = []
    # Dodawanie od końca zachowuje kolejność z GetCapabilities w drzewie warstw.
    for name, title, crs in reversed(layer_specs):
        source = (
            f"url={service_url}"
            f"&layers={name}"
            "&styles="
            "&format=image/png"
            f"&crs={crs}"
        )
        layer = QgsRasterLayer(source, title, "wms")
        if not layer.isValid():
            failed_titles.append(title)
            continue

        project.addMapLayer(layer, False)
        group.insertLayer(0, layer)
        added_layers.append(layer)

    if not added_layers:
        QMessageBox.critical(
            parent,
            "BDOT10k",
            f"Nie udało się utworzyć warstwy WMS „{display_name}”.",
        )
        return

    group.setExpanded(True)
    iface.messageBar().pushSuccess(
        "BDOT10k",
        f"Dodano mapę „{display_name}” z usługi Geoportalu.",
    )

    if failed_titles:
        QMessageBox.warning(
            parent,
            "BDOT10k",
            "Część warstw usługi WMS nie mogła zostać wczytana:\n\n"
            + "\n".join(f"• {title}" for title in failed_titles),
        )


def _parse_wms_capabilities(xml_bytes, project_crs):
    """Zwróć listę (nazwa, tytuł, CRS) dla nazwanych warstw liściowych WMS."""
    document = QDomDocument()
    result = document.setContent(xml_bytes)
    ok = result[0] if isinstance(result, tuple) else bool(result)
    if not ok:
        return []

    nodes = document.elementsByTagName("Layer")
    all_named = []
    leaf_named = []

    for index in range(nodes.count()):
        element = nodes.at(index).toElement()
        if element.isNull():
            continue

        name = element.firstChildElement("Name").text().strip()
        if not name:
            continue
        title = element.firstChildElement("Title").text().strip() or name
        crs = _choose_layer_crs(element, project_crs)
        if not crs:
            continue

        spec = (name, title, crs)
        all_named.append(spec)
        if element.firstChildElement("Layer").isNull():
            leaf_named.append(spec)

    return leaf_named or all_named


def _choose_layer_crs(layer_element, project_crs):
    """Wybierz CRS obsługiwany przez warstwę, uwzględniając dziedziczenie WMS."""
    available = []
    current = layer_element

    while not current.isNull():
        child = current.firstChild()
        while not child.isNull():
            child_element = child.toElement()
            if not child_element.isNull() and child_element.tagName() in ("CRS", "SRS"):
                for value in child_element.text().split():
                    if value and value not in available:
                        available.append(value)
            child = child.nextSibling()

        parent = current.parentNode().toElement()
        if parent.isNull() or parent.tagName() != "Layer":
            break
        current = parent

    preferred = [project_crs, "EPSG:2180", "EPSG:3857", "EPSG:4326"]
    for crs in preferred:
        if crs and crs in available:
            return crs
    return available[0] if available else "EPSG:2180"


def _safe_unlink(path):
    """Usuń plik pomocniczy bez zgłaszania błędu przy sprzątaniu po operacji."""
    try:
        if path.exists():
            path.unlink()
    except OSError:
        pass
